REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA registry FROM pipeline_writer;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA silver FROM pipeline_writer;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA bronze FROM pipeline_writer;
REVOKE ALL PRIVILEGES ON SCHEMA registry FROM pipeline_writer;
REVOKE ALL PRIVILEGES ON SCHEMA silver FROM pipeline_writer;
REVOKE ALL PRIVILEGES ON SCHEMA bronze FROM pipeline_writer;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA registry FROM app_reader;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA silver FROM app_reader;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA bronze FROM app_reader;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA gold FROM app_reader;
REVOKE ALL PRIVILEGES ON SCHEMA registry FROM app_reader;
REVOKE ALL PRIVILEGES ON SCHEMA silver FROM app_reader;
REVOKE ALL PRIVILEGES ON SCHEMA bronze FROM app_reader;
REVOKE ALL PRIVILEGES ON SCHEMA gold FROM app_reader;

DROP SCHEMA IF EXISTS gold CASCADE;
DROP ROLE IF EXISTS pipeline_writer;
DROP ROLE IF EXISTS app_reader;

DROP SCHEMA IF EXISTS registry CASCADE;
DROP SCHEMA IF EXISTS silver CASCADE;
DROP SCHEMA IF EXISTS bronze CASCADE;
DROP SCHEMA IF EXISTS metadata CASCADE;
DROP SCHEMA IF EXISTS raw CASCADE;
DROP SCHEMA IF EXISTS standardized CASCADE;
DROP SCHEMA IF EXISTS curated CASCADE;
DROP SCHEMA IF EXISTS ops CASCADE;